name: Kno
favicon: null
layout_spectrum: 0.75846
typography_spectrum: 0.399
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#767f9e'
    - '#060405'
    - '#033b6c'
    - '#d10006'
    - '#d7b3a3'
  brandStrength: 0.75
  lightness: 0.8203204504679888
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
