name: Kno
favicon: null
layout_spectrum: 0.6867822979111224
typography_spectrum: 0.3554328454192728
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8354936554096639
  lightness: 0.8203204504679888
  saturation: 0.803267081733793
  rhythmicContrast: 0.07396504376083612
purpose: []
